name: Format-and-Fail
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  biomejs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
        with:
          version: '1.9.4'
      - run: biome ci --formatter-enabled=true --organize-imports-enabled=true --linter-enabled=false ./web biome.json package.json README.md
