name: Format-and-Fail
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  biomejs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
        with:
          version: '1.9.4'
      - run: biome ci ./web biome.json package.json
